In [48]:
import json
with open("data/svm-ssq/final_data.json", "r", encoding="utf-8") as f:
    train_data = json.load(f)

In [75]:
from joblib import dump
from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler

mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], max_iter=500, solver='adam', learning_rate_init=0.001,
                       random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(train_data['ball_0']['x_data'], train_data['ball_0']['y_data'])
dump(pipeline, 'data/svm-ssq/model/ball_mlp_0.joblib')


['data/svm-ssq/model/ball_mlp_0.joblib']

In [76]:
mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], max_iter=750, solver='adam', learning_rate_init=0.01,
                       random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(train_data['ball_1']['x_data'], train_data['ball_1']['y_data'])
dump(pipeline, 'data/svm-ssq/model/ball_mlp_1.joblib')

['data/svm-ssq/model/ball_mlp_1.joblib']

In [77]:
mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], max_iter=1000, solver='adam', learning_rate_init=0.01,
                       random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(train_data['ball_2']['x_data'], train_data['ball_2']['y_data'])
dump(pipeline, 'data/svm-ssq/model/ball_mlp_2.joblib')

['data/svm-ssq/model/ball_mlp_2.joblib']

In [78]:
mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], max_iter=1250, solver='adam', learning_rate_init=0.01,
                       random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(train_data['ball_3']['x_data'], train_data['ball_3']['y_data'])
dump(pipeline, 'data/svm-ssq/model/ball_mlp_3.joblib')

['data/svm-ssq/model/ball_mlp_3.joblib']

In [79]:
mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], max_iter=1500, solver='adam', learning_rate_init=0.01,
                       random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(train_data['ball_4']['x_data'], train_data['ball_4']['y_data'])
dump(pipeline, 'data/svm-ssq/model/ball_mlp_4.joblib')

['data/svm-ssq/model/ball_mlp_4.joblib']

In [80]:
mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], max_iter=2000, solver='adam', learning_rate_init=0.05,
                       random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(train_data['ball_5']['x_data'], train_data['ball_5']['y_data'])
dump(pipeline, 'data/svm-ssq/model/ball_mlp_5.joblib')

['data/svm-ssq/model/ball_mlp_5.joblib']

In [82]:
mlp_reg = MLPRegressor(hidden_layer_sizes=[50, 50, 50], max_iter=2500, solver='adam', learning_rate_init=0.01,
                       random_state=42)
pipeline = make_pipeline(StandardScaler(), mlp_reg)
pipeline.fit(train_data['ball_6']['x_data'], train_data['ball_6']['y_data'])
dump(pipeline, 'data/svm-ssq/model/ball_mlp_6.joblib')

['data/svm-ssq/model/ball_mlp_6.joblib']

In [1]:
import sxtwl
def outTianGanDiZhi(year, month, day):
    day = sxtwl.fromSolar(year, month, day)
    Gan = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]
    Zhi = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]
    tianGanDiZhi_years = ['甲子', '乙丑', '丙寅', '丁卯', '戊辰', '己巳', '庚午', '辛未', '壬申', '癸酉',
                          '甲戌', '乙亥', '丙子', '丁丑', '戊寅', '己卯', '庚辰', '辛巳', '壬午', '癸未',
                          '甲申', '乙酉', '丙戌', '丁亥', '戊子', '己丑', '庚寅', '辛卯', '壬辰', '癸巳',
                          '甲午', '乙未', '丙申', '丁酉', '戊戌', '己亥', '庚子', '辛丑', '壬寅', '癸卯',
                          '甲辰', '乙巳', '丙午', '丁未', '戊申', '己酉', '庚戌', '辛亥', '壬子', '癸丑',
                          '甲寅', '乙卯', '丙辰', '丁巳', '戊午', '己未', '庚申', '辛酉', '壬戌', '癸亥']

    def getGZIndex(tgDz):
        for i in range(len(tianGanDiZhi_years)):
            if tgDz == tianGanDiZhi_years[i]:
                return i
    
    result = []
    # 年
    yTG = day.getYearGZ(True)
    gz_year = Gan[yTG.tg] + Zhi[yTG.dz]
    result.append(getGZIndex(gz_year))
    
    # 月
    mTG = day.getMonthGZ()
    gz_month = Gan[mTG.tg] + Zhi[mTG.dz]
    result.append(getGZIndex(gz_month))
    
    # 日
    dTG = day.getDayGZ()
    gz_day = Gan[dTG.tg] + Zhi[dTG.dz]
    result.append(getGZIndex(gz_day))
    
    # 生肖
    result.append(yTG.dz)
    
    return result

In [2]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_mlp_0.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22]]


array([1.88430688])

In [3]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_mlp_1.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(2)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  2]]


array([5.52329673])

In [4]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_mlp_2.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(2)
my_data.append(6)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  2  6]]


array([9.71000507])

In [5]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_mlp_3.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(2)
my_data.append(6)
my_data.append(10)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  2  6 10]]


array([17.57463256])

In [6]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_mlp_4.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(2)
my_data.append(6)
my_data.append(10)
my_data.append(18)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  2  6 10 18]]


array([25.67572522])

In [8]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_mlp_5.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(2)
my_data.append(6)
my_data.append(10)
my_data.append(18)
my_data.append(26)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  2  6 10 18 26]]


array([27.2727982])

In [9]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_mlp_6.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(2)
my_data.append(6)
my_data.append(10)
my_data.append(18)
my_data.append(26)
my_data.append(27)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  2  6 10 18 26 27]]


array([8.2289399])