In [2]:
# 获取数据
import requests
import json

headers = {
    'server': 'wswaf'
}

response = requests.get('https://www.cwl.gov.cn/cwl_admin/front/cwlkj/search/kjxx/findDrawNotice?name=ssq&issueCount=&issueStart=&issueEnd=&dayStart=&dayEnd=&pageNo=1&pageSize=2000&week=&systemType=PC', headers=headers)

if response.status_code == 200:
    # print(response.json())
    print(response.json()['total'])
    print(len(response.json()['result']))

    json_str = json.dumps(response.json(), indent=4)
    with open("data/svm-ssq/data.json", "w", encoding="utf-8") as f:
        f.write(json_str)

1897
1897


In [2]:
import json
def week_to_number(week):
    if week == '一':
        return 0
    if week == '二':
        return 1
    if week == '三':
        return 2
    if week == '四':
        return 3
    if week == '五':
        return 4
    if week == '六':
        return 6
    if week == '七':
        return 6
    return -1
    
    
with open("data/svm-ssq/data.json", "r", encoding="utf-8") as f:
    data = json.load(f)
    
for info in data['result']:
    print(info['date'].replace('(', ' ').replace(')', '').split(' ')[0].split('-'))
    print(week_to_number(info['week']))
    print(info['red'].split(','))
    print(info['blue'])
    print(info['content'].split(','))
    print()

['2025', '08', '07']
3
['06', '11', '12', '21', '27', '28']
15
['黑龙江1注，上海1注，河南2注，湖北40注，湖南3注，广东1注，云南2注，新疆1注，共51注。']

['2025', '08', '05']
1
['04', '06', '08', '18', '31', '33']
05
['浙江1注，福建2注，云南1注，新疆1注，共5注。']

['2025', '08', '03']
-1
['01', '03', '13', '18', '21', '25']
06
['上海1注，浙江1注，安徽1注，甘肃1注，共4注。']

['2025', '07', '31']
3
['02', '06', '14', '15', '24', '26']
08
['福建1注，江西1注，广东1注，共3注。']

['2025', '07', '29']
1
['02', '06', '08', '10', '17', '24']
06
['黑龙江1注，上海2注，浙江1注，山东2注，河南1注，湖南3注，甘肃5注，青海1注，共16注。']

['2025', '07', '27']
-1
['11', '14', '15', '18', '21', '24']
13
['广东1注，云南11注，陕西5注，共17注。']

['2025', '07', '24']
3
['06', '08', '10', '14', '24', '33']
15
['北京1注，内蒙古2注，重庆1注，云南1注，深圳1注，共6注。']

['2025', '07', '22']
1
['10', '15', '16', '17', '27', '29']
12
['浙江1注，山东1注，河南1注，湖北1注，湖南1注，广东1注，四川1注，深圳1注，共8注。']

['2025', '07', '20']
-1
['04', '06', '09', '14', '32', '33']
11
['浙江1注，江西1注，山东1注，云南1注，共4注。']

['2025', '07', '17']
3
['03', '06', '18', '20', '23', '28']
05
['浙江2注，广东2注，四川1注，青海1注，共6注。']

['20

In [3]:
import sxtwl
def outTianGanDiZhi(year, month, day):
    day = sxtwl.fromSolar(year, month, day)
    Gan = ["甲", "乙", "丙", "丁", "戊", "己", "庚", "辛", "壬", "癸"]
    Zhi = ["子", "丑", "寅", "卯", "辰", "巳", "午", "未", "申", "酉", "戌", "亥"]
    tianGanDiZhi_years = ['甲子', '乙丑', '丙寅', '丁卯', '戊辰', '己巳', '庚午', '辛未', '壬申', '癸酉',
                          '甲戌', '乙亥', '丙子', '丁丑', '戊寅', '己卯', '庚辰', '辛巳', '壬午', '癸未',
                          '甲申', '乙酉', '丙戌', '丁亥', '戊子', '己丑', '庚寅', '辛卯', '壬辰', '癸巳',
                          '甲午', '乙未', '丙申', '丁酉', '戊戌', '己亥', '庚子', '辛丑', '壬寅', '癸卯',
                          '甲辰', '乙巳', '丙午', '丁未', '戊申', '己酉', '庚戌', '辛亥', '壬子', '癸丑',
                          '甲寅', '乙卯', '丙辰', '丁巳', '戊午', '己未', '庚申', '辛酉', '壬戌', '癸亥']

    def getGZIndex(tgDz):
        for i in range(len(tianGanDiZhi_years)):
            if tgDz == tianGanDiZhi_years[i]:
                return i
    
    result = []
    # 年
    yTG = day.getYearGZ(True)
    gz_year = Gan[yTG.tg] + Zhi[yTG.dz]
    result.append(getGZIndex(gz_year))
    
    # 月
    mTG = day.getMonthGZ()
    gz_month = Gan[mTG.tg] + Zhi[mTG.dz]
    result.append(getGZIndex(gz_month))
    
    # 日
    dTG = day.getDayGZ()
    gz_day = Gan[dTG.tg] + Zhi[dTG.dz]
    result.append(getGZIndex(gz_day))
    
    # 生肖
    result.append(yTG.dz)
    
    return result


def outAreaCode(result,areas):
    areas_code = []
    provinces = [
        "河北", "山西", "吉林", "辽宁", "黑龙江",
        "陕西", "甘肃", "青海", "山东", "福建",
        "浙江", "台湾", "河南", "湖北", "湖南",
        "江西", "江苏", "安徽", "广东", "海南",
        "四川", "贵州", "云南",
        "内蒙古", "广西", "西藏", "宁夏", "新疆",
        "北京", "天津", "上海", "重庆",
        "香港", "澳门"
    ]

    def outNumber(province, areas):
        if len(areas) == 0:
            return -1
        for i in range(len(areas) - 1):
            if province in areas[i]:
                return i
        return -1
                
    for province in provinces:
        code = outNumber(province,areas)
        if code == -1:
            continue
        areas_code.append(code)
    
    if len(areas_code) == 0:
        areas_code.append(-1)
    return areas_code

x_data = []
y_data = []
for info in data['result']:
    date = info['date'].replace('(', ' ').replace(')', '').split(' ')[0].split('-')
    x_result = outTianGanDiZhi(int(date[0]), int(date[1]), int(date[2]))
    areas_code = outAreaCode(x_result,info['content'].split(','))
    for code in areas_code:
        x_temp_result = x_result.copy()
        x_temp_result.append(code)
        x_data.append(x_temp_result)

        y_result = list(map(int, info['red'].split(',')))
        y_result.append(int(info['blue']))
        y_data.append(y_result)
    # x_data.append(x_result)
    # y_result = list(map(int, info['red'].split(',')))
    # y_result.append(int(info['blue']))
    # y_data.append(y_result)
    
print(x_data)
print(y_data)
all_data = []
ball_0 = {'x_data': x_data, 'y_data': []}
for info in y_data:
    ball_0['y_data'].append(info[0])

ball_1 = {'x_data': [], 'y_data': []}
for info in y_data:
    ball_1['y_data'].append(info[1])
for i in range(len(x_data)):
    info = x_data[i].copy()
    info.append(y_data[i][0])
    ball_1['x_data'].append(info)
    
ball_2 = {'x_data': [], 'y_data': []}
for info in y_data:
    ball_2['y_data'].append(info[2])
for i in range(len(x_data)):
    info = x_data[i].copy()
    info.append(y_data[i][0])
    info.append(y_data[i][1])
    ball_2['x_data'].append(info)
    
ball_3 = {'x_data': [], 'y_data': []}
for info in y_data:
    ball_3['y_data'].append(info[3])
for i in range(len(x_data)):
    info = x_data[i].copy()
    info.append(y_data[i][0])
    info.append(y_data[i][1])
    info.append(y_data[i][2])
    ball_3['x_data'].append(info)

ball_4 = {'x_data': [], 'y_data': []}
for info in y_data:
    ball_4['y_data'].append(info[4])
for i in range(len(x_data)):
    info = x_data[i].copy()
    info.append(y_data[i][0])
    info.append(y_data[i][1])
    info.append(y_data[i][2])
    info.append(y_data[i][3])
    ball_4['x_data'].append(info)
    
ball_5 = {'x_data': [], 'y_data': []}
for info in y_data:
    ball_5['y_data'].append(info[5])
for i in range(len(x_data)):
    info = x_data[i].copy()
    info.append(y_data[i][0])
    info.append(y_data[i][1])
    info.append(y_data[i][2])
    info.append(y_data[i][3])
    info.append(y_data[i][4])
    ball_5['x_data'].append(info)
    
ball_6 = {'x_data': [], 'y_data': []}
for info in y_data:
    ball_6['y_data'].append(info[6])
for i in range(len(x_data)):
    info = x_data[i].copy()
    info.append(y_data[i][0])
    info.append(y_data[i][1])
    info.append(y_data[i][2])
    info.append(y_data[i][3])
    info.append(y_data[i][4])
    info.append(y_data[i][5])
    ball_6['x_data'].append(info)
final_data = {
    'ball_0': ball_0,
    'ball_1': ball_1,
    'ball_2': ball_2,
    'ball_3': ball_3,
    'ball_4': ball_4,
    'ball_5': ball_5,
    'ball_6': ball_6,
}

json_str = json.dumps(final_data, indent=4)
with open("data/svm-ssq/final_data.json", "w", encoding="utf-8") as f:
    f.write(json_str)


[[41, 20, 44, 5, -1], [41, 19, 42, 5, -1], [41, 19, 40, 5, -1], [41, 19, 37, 5, -1], [41, 19, 35, 5, -1], [41, 19, 33, 5, -1], [41, 19, 30, 5, -1], [41, 19, 28, 5, -1], [41, 19, 26, 5, -1], [41, 19, 23, 5, -1], [41, 19, 21, 5, -1], [41, 19, 19, 5, -1], [41, 19, 16, 5, -1], [41, 19, 14, 5, -1], [41, 18, 12, 5, -1], [41, 18, 9, 5, -1], [41, 18, 7, 5, -1], [41, 18, 5, 5, -1], [41, 18, 2, 5, -1], [41, 18, 0, 5, -1], [41, 18, 58, 5, -1], [41, 18, 55, 5, -1], [41, 18, 53, 5, -1], [41, 18, 51, 5, -1], [41, 18, 48, 5, -1], [41, 18, 46, 5, -1], [41, 18, 44, 5, -1], [41, 18, 41, 5, -1], [41, 17, 39, 5, -1], [41, 17, 37, 5, -1], [41, 17, 34, 5, -1], [41, 17, 32, 5, -1], [41, 17, 30, 5, -1], [41, 17, 27, 5, -1], [41, 17, 25, 5, -1], [41, 17, 23, 5, -1], [41, 17, 20, 5, -1], [41, 17, 18, 5, -1], [41, 17, 16, 5, -1], [41, 17, 13, 5, -1], [41, 17, 11, 5, -1], [41, 16, 9, 5, -1], [41, 16, 6, 5, -1], [41, 16, 4, 5, -1], [41, 16, 2, 5, -1], [41, 16, 59, 5, -1], [41, 16, 57, 5, -1], [41, 16, 55, 5, -1], 

In [4]:
import json
with open("data/svm-ssq/final_data.json", "r", encoding="utf-8") as f:
    train_data = json.load(f)

In [89]:
from sklearn.svm import SVC
from joblib import dump

svm_clf = SVC(random_state=42)
svm_clf.fit(train_data['ball_0']['x_data'], train_data['ball_0']['y_data'])
dump(svm_clf, 'data/svm-ssq/model/ball_0.joblib')

['data/svm-ssq/model/ball_0.joblib']

In [91]:
svm_clf = SVC(random_state=42)
svm_clf.fit(train_data['ball_1']['x_data'], train_data['ball_1']['y_data'])
dump(svm_clf, 'data/svm-ssq/model/ball_1.joblib')

['data/svm-ssq/model/ball_1.joblib']

In [92]:
svm_clf = SVC(random_state=42)
svm_clf.fit(train_data['ball_2']['x_data'], train_data['ball_2']['y_data'])
dump(svm_clf, 'data/svm-ssq/model/ball_2.joblib')

['data/svm-ssq/model/ball_2.joblib']

In [93]:
svm_clf = SVC(random_state=42)
svm_clf.fit(train_data['ball_3']['x_data'], train_data['ball_3']['y_data'])
dump(svm_clf, 'data/svm-ssq/model/ball_3.joblib')

['data/svm-ssq/model/ball_3.joblib']

In [94]:
svm_clf = SVC(random_state=42)
svm_clf.fit(train_data['ball_4']['x_data'], train_data['ball_4']['y_data'])
dump(svm_clf, 'data/svm-ssq/model/ball_4.joblib')

['data/svm-ssq/model/ball_4.joblib']

In [95]:
svm_clf = SVC(random_state=42)
svm_clf.fit(train_data['ball_5']['x_data'], train_data['ball_5']['y_data'])
dump(svm_clf, 'data/svm-ssq/model/ball_5.joblib')

['data/svm-ssq/model/ball_5.joblib']

In [96]:
svm_clf = SVC(random_state=42)
svm_clf.fit(train_data['ball_6']['x_data'], train_data['ball_6']['y_data'])
dump(svm_clf, 'data/svm-ssq/model/ball_6.joblib')

['data/svm-ssq/model/ball_6.joblib']

In [12]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_0.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22]]


array([3])

In [13]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_1.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(3)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  3]]


array([9])

In [14]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_2.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(3)
my_data.append(9)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  3  9]]


array([13])

In [15]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_3.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(3)
my_data.append(9)
my_data.append(13)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  3  9 13]]


array([19])

In [16]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_4.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(3)
my_data.append(9)
my_data.append(13)
my_data.append(19)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  3  9 13 19]]


array([25])

In [17]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_5.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(3)
my_data.append(9)
my_data.append(13)
my_data.append(19)
my_data.append(25)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  3  9 13 19 25]]


array([30])

In [18]:
from joblib import load
import numpy as np

# 加载之前保存的模型
loaded_svm_clf = load('data/svm-ssq/model/ball_6.joblib')
my_data = outTianGanDiZhi(2025, 8, 10)
my_data.append(22)
my_data.append(3)
my_data.append(9)
my_data.append(13)
my_data.append(19)
my_data.append(25)
my_data.append(30)
input_data = np.array(my_data) 
input_data_2d = input_data.reshape(1, -1)
print(input_data_2d)
loaded_svm_clf.predict(input_data_2d)

[[41 20 47  5 22  3  9 13 19 25 30]]


array([3])